version: "2.2"
services:
### db ###################################################
  db:
    image: mysql:latest
    command: "--default-authentication-plugin=mysql_native_password --innodb_use_native_aio=0"
    # build:
    # context: ./data
      # args:
        # - MYSQL_VERSION=${MYSQL_VERSION}
    ports: 
        - "3306:3306"
    environment:
        MYSQL_DATABASE: ${MYSQL_DATABASE}
        MYSQL_USER: ${MYSQL_USER}
        MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        TZ: ${WORKSPACE_TIMEZONE}
    volumes:
        # - ${MYSQL_ENTRYPOINT_INITDB}:/docker-entrypoint-initdb.d
        - ${DATA_PATH_HOST}:/var/lib/mysql
    networks:
        - default
## phpMyAdmin ###########################################
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    # build: ./phpmyadmin
    links: 
        - db:db
    ports:
        - 8000:80
    environment:
        PMA_HOST: db
        MYSQL_USER: ${MYSQL_USER}
        MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}